name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/dockerwaiter/dockerwaiter.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/dockerwaiter.sln
    - name: Pack
      run: dotnet pack ./src/dockerwaiter.sln  -o .
    - name: Push
      env:
        API_KEY: ${{ secrets.ApiKey }}
      run: dotnet nuget push ./dockerwaiter.*.nupkg -k $API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate

    
